from django.db import models

class FoodTruck(models.Model):
    # locationid = models.BigIntegerField()
    applicant = models.CharField(max_length=200, default='')
    # facilityType = models.CharField(max_length=50, default='')
    # cnn = models.IntegerField(default=0)
    # locationDescription = models.CharField(max_length=500, default='')
    address = models.CharField(max_length=100, default='')
    # blocklot = models.BigIntegerField(default=0)
    # block = models.IntegerField(default=0)
    # lot = models.IntegerField(default=0)
    # permit = models.CharField(max_length=100, default='')
    # status = models.CharField(max_length=100, default='')
    foodItems = models.CharField(max_length=500, default='')
    # x = models.FloatField(default=0)
    # y = models.FloatField(default=0)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    # schedule = models.CharField(max_length=1000, default='')
    # dayHours = models.CharField(max_length=100, default='')
    # NOISent = models.CharField(max_length=100, default='')
    # approved = models.CharField(max_length=100, default='')
    # recieved = models.BigIntegerField(default=0)
    # priorPermit = models.IntegerField(default=0)
    # expirationDate = models.CharField(max_length=100, default='')
    # location = models.CharField(max_length=100, default='')
    # firePreventionDistrict = models.IntegerField(default=0)
    # policeDistricts = models.IntegerField(default=0)
    # supervisorDistrict = models.IntegerField(default=0)
    # zipCode = models.IntegerField(default=0)
    # neighborhoods = models.IntegerField(default=0)
